version: "3.7"

services:
  file-server-1:
    build:
      context: .
    volumes:
      - ./:/shared/folder #Current directory
  file-server-2:
    build:
      context: .
    volumes:
     - /etc:/shared/folder # Directory /etc
  proxy:
    image: nginx:1.17
    volumes:
      - ./configuration.nginx:/etc/nginx/nginx.conf:ro
    ports:
      - 8888:8888  # Set which ports to trigger